steps:
  - label: 'Upload App Distribution Internal'
    if: build.branch == "master" || build.branch == "release" || build.branch =~ /^v[0-9]+.*/
    key: 'upload-firebase-internal'
    command: 'ci/upload_app_distribution.sh internal-beta internal'

  - label: 'Upload App Distribution Rinkeby'
    if: build.branch == "master" || build.branch == "release" || build.branch =~ /^v[0-9]+.*/
    key: 'upload-firebase-rinkeby'
    command: 'ci/upload_app_distribution.sh rinkeby-release-internal rinkeby'

  - label: 'Upload App Distribution Mainnet'
    if: build.branch == "master" || build.branch == "release" || build.branch =~ /^v[0-9]+.*/
    key: 'upload-firebase-mainnet'
    command: 'ci/upload_app_distribution.sh mainnet-release-internal release'

  - label: 'Upload Github Release'
    if: build.branch =~ /^v[0-9]+.*/
    key: 'upload-github'
    command: 'ci/upload_to_github.sh'

